# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0.28-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    depends_on: [db]
    restart: always
    ports:
      - 8080:8080